### ISSUE TITLE
Loop over array specified in transform

### ISSUE THREAD

**Issue by kakins** [WorkMaze/JUST.net#164]
I want a sort of enum match functionality...

Source
```
{
  someProp: 0
}
```

Transform
```
// Some way of defining an array and indexing into it via the source value
{
  newProp: ["abc", "xyz"][#valueof($.someProp)]
}
```

Expected Result
```
{
  newProp: "abc"
}
```

Is there a way to do this without using multipe `ifcondition` statements?

**Comment by Courela** [comment]
If your array is in the input, you could do something like this:

```JSON
//Input
{ 
  "someProp": 0,
  "arr": [ "abc", "xyz" ]
}

//Transformer
{
  "newProp": "#valueof(#xconcat($.arr[,#valueof($.oldProp),]))"
}
```

Basically you construct a dynamic jsonpath expression (or other languange for that matter). This will result in 
```JSON
#valueof($.arr[0])
```

**Comment by kakins** [comment]
@Courela Thanks.  That's one possibility.  Is there any way we could define the array inside the transformer so that it doesn't have to exist in the source?

**Comment by Courela** [comment]
That option doesn't exist, no. The purpose of this tool is to be an alternative to XSLT, transforming JSON into JSON, I don't know if that option exists in XSLT.

Since you want to use values from input, I don't see any other way of doing it without using #xconcat to generate a dynamic expression, since arguments of #xconcat can be another functions. 
What was your idea for applying it directly to #valueof?

**Comment by kakins** [comment]
That makes sense.  Honestly I haven't dug into the spec of XSLT to see if that functionality exists.  So no worries... thanks for the help!

My first thought playing with the library was that I would be able to do something like 
```
myProp: "#valueof($.myArray[0])"
```
`$.myArray` notation already seems like JsonPath notation?  so I'm just wondering why the array index accessor doesn't (or wouldn't) work here.  Or any JsonPath expression/query for that matter.

**Comment by Courela** [comment]
That expression, and any other JsonPath expression, should work in #valueof. An external library, Newtonsoft Json , is responsible to handle the JsonPath expression, but that is valid expression.
Since you mentioned the index (0 in this case) was in the source, a dynamic expression is needed. If you know it shorthand, there's no need for that.

**Comment by kakins** [comment]
Ahhh, I see now.  When using  a JsonPath expression where part of the expression is retrieved via a function (e.g. #valueof), then we'd need to construct it dynamically.  Thank makes sense.  Thanks!
