### ISSUE TITLE
[question] How to get a specific index from an array filter

### ISSUE THREAD

**Issue by quintelab** [WorkMaze/JUST.net#236]
Hi,

I have a scenario where I am applying a filter to an array:

`{
    "productCode": "#valueof($.orderLine[?(@.fulfillmentStatus =~ /$*Canceled*$//)].itemId)"
}`

Data:
`{
    "createdTimestamp": "2022-06-02T15:38:02.783",
    "orderLine": [
        {
            "itemId": "883849795227",
            "fulfillmentStatus": "Canceled"
        },
        {
            "itemId": "194998065544",
            "fulfillmentStatus": "Canceled"
        },
        {
            "itemId": "194998065500",
            "fulfillmentStatus": "Nothing"
        }
    ]
}`

It returns as expected:
`{
    "productCode": [
        "883849795227",
        "193623064594"
    ]
}`

I would like to be able to get the first or the last index of this productCode array. How can I get a specific index after my filter ?

Thank you!!

**Comment by Courela** [comment]
This works without using #loop:
```JSON
{
  "productCode": "#applyover({ 'arr': '#valueof($.orderLine[?(@.fulfillmentStatus =~ /Canceled/)].itemId)' }, '#valueof($.arr[0])')"
}
```

This will perform two transformations with one transformer.
Two things to note: 
- the second parameter of #applyover (second transformation) selects the item based on hardcoded index
- for this transformer to work one has to change the escape char, since the default is /, which is used in regex. Changing it to pipe (|) will do the job
```CSHARP
var result = new JsonTransformer(new JUSTContext { EscapeChar = '|'}).Transform(transformer, input);
```
